# .github/workflows/dependent-pipeline.yml

name: Dependent Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Job 1 Tasks
        run: |
          echo "This is Job 1"
          # Simulating some task, for example, a build
          echo "Job 1 complete."

  job2:
    runs-on: ubuntu-latest
    needs: job1  # This job will only run if job1 is successful

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Job 2 Tasks
        run: |
          echo "This is Job 2, which depends on Job 1."
          # Simulating a task that requires job1 to be successful
          echo "Job 2 complete."
