trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: Build Job
    steps:
    - script: |
        echo "Building the application..."
        # Simulate building some files
        mkdir build_output
        echo "File 1" > build_output/file1.txt
        echo "File 2" > build_output/file2.txt
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Build Artifact'
      inputs:
        targetPath: 'build_output'
        artifact: 'build_artifacts'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build # Dependency on the Build stage
  jobs:
  - job: DeployJob
    displayName: Deploy Job
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Build Artifact'
      inputs:
        artifact: 'build_artifacts'
        path: '$(System.ArtifactsDirectory)/build_artifacts'
    - script: |
        echo "Deploying the application..."
        # Simulate using the downloaded artifacts
        ls $(System.ArtifactsDirectory)/build_artifacts
        cat $(System.ArtifactsDirectory)/build_artifacts/file1.txt
        cat $(System.ArtifactsDirectory)/build_artifacts/file2.txt
    - script: |
        echo "Deploying to development environment..."
        # Simulate environment-specific deployment
        echo "Development deployment steps..."