trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: QuickBuild
  displayName: Quick Build
  jobs:
  - job: SimpleBuild
    displayName: Simple Build Job
    steps:
    - script: echo "Build successful." > build.log
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Build Log'
      inputs:
        targetPath: 'build.log'
        artifact: 'build_log'
        publishLocation: 'pipeline'

- stage: QuickTest
  displayName: Quick Test
  dependsOn: QuickBuild
  jobs:
  - job: SimpleTest
    displayName: Simple Test Job
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Build Log'
      inputs:
        artifact: 'build_log'
        path: '$(System.ArtifactsDirectory)'
    - script: |
        cat $(System.ArtifactsDirectory)/build.log
        echo "Test successful."

- stage: QuickDeploy
  displayName: Quick Deploy
  dependsOn: QuickTest
  jobs:
  - job: SimpleDeploy
    displayName: Simple Deploy Job
    steps:
    - script: echo "Deployment successful."