trigger:
  branches:
    include:
      - main  # Replace with your desired branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Checkout@2  # Checkout task
    displayName: 'Checkout Code'

  - script: |
      echo "Pipeline is working!"
    displayName: 'Test Step'
