trigger:
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'test'
    publishLocation: 'pipeline'
  branches:
    include:
      - main  # Trigger on changes to 'main' branch
