name: Sample CI Pipeline

# Trigger the pipeline on push or pull request
on:
  push:
    branches:
      - main  # Runs on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Runs on pull requests targeting 'main' branch

# Define the jobs to run in the pipeline
jobs:
  build:
    runs-on: ubuntu-latest  # This runs the pipeline on an Ubuntu environment

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python (as an example, this can be any language/tool you use)
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Choose the Python version you want

    # Step 3: Install dependencies (if using a Python project as an example)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests (if applicable, for example, running pytest in Python)
    - name: Run tests
      run: |
        pytest  # or any testing command like 'npm test' for Node.js, etc.

    # Step 5: Optionally, deploy or build your app here (depends on your project)
    - name: Deploy (optional)
      run: |
        echo "Deploying your app..."  # Replace with actual deployment commands
